package models

import (
	"database/sql"

	_ "github.com/go-sql-driver/mysql"

	"encoding/json"

	"github.com/yidane/gotest/beegoTest/models/grid"
	"github.com/yidane/gotest/beegoTest/models/grid/data"
	"github.com/yidane/gotest/beegoTest/models/grid/style"
)

//GetDefine 获取报表数据
func GetDefine() (data.Define, style.Grid) {
	db, err := sql.Open("mysql", "dbn_admin:dbn002385@tcp(172.16.200.65:4501)/NXin_Qlw_Business?charset=utf8")
	defer db.Close()
	if err != nil {
		panic(err)
	}
	rs, err := db.Query(`Select  Distinct 
						NXin_Qlw_Business.SA_Order.NumericalOrder,
						NXin_Qlw_Business.SA_Order.DataDate,
						NXin_Qlw_Business.SA_Order.PaymentStatus,
						NXin_Qlw_Business.SA_Order.PaymentAmount,
						NXin_Qlw_Business.SA_Order.Consignee From NXin_Qlw_Business.SA_Order
						Inner Join
						NXin_Qlw_Business.SA_OrderDetail ON NXin_Qlw_Business.SA_Order.NumericalOrder=NXin_Qlw_Business.SA_OrderDetail.NumericalOrder`)
	if err != nil {
		panic(err)
	}

	define := data.Define{}
	define.ColumnCollection = []string{"NumericalOrder", "DataDate", "PaymentStatus", "PaymentAmount", "Consignee"}
	rows := []data.DefineRow{}
	for rs.Next() {
		var NumericalOrder *int64
		var DataDate *string
		var PaymentStatus *string
		var PaymentAmount *string
		var Consignee *string
		err = rs.Scan(&NumericalOrder, &DataDate, &PaymentStatus, &PaymentAmount, &Consignee)
		if err != nil {
			panic(err)
		}
		rows = append(rows, data.DefineRow{CellCollection: []interface{}{NumericalOrder, DataDate, 123456789, PaymentAmount, Consignee}})
	}
	define.RowCollection = rows

	//查询数据行为空
	//define.RowCollection = nil

	//生成Grid
	g := style.Grid{
		RowCollection: []style.GridRow{
			style.CreateHeader("DataDate", "NumericalOrder", "表头", "表头", "Consignee"),
			style.CreateHeader("DataDate", "NumericalOrder", "PaymentStatus", "PaymentAmount", "Consignee"),
		},
	}
	// g.SubTotalColor = "#f8f6f2"
	// g.TotalColor = "#f8f6f2"
	//合并表头
	g.MergedCells = []style.MergeInfo{
		style.NewMergeInfo(0, 0, 1, 0),
		style.NewMergeInfo(0, 1, 1, 1),
		style.NewMergeInfo(0, 2, 0, 3),
		style.NewMergeInfo(0, 4, 1, 4),
	}
	dataDateCell := style.GridCell{
		Value:         "[" + "DataDate" + "]",
		TextAlign:     "center",
		VerticalAlign: "center",
		Link:          "http://www.baidu.com",
		CellProperty: style.GridCellProperty{
			IsGroup: true,
		},
	}
	numericalOrderCell := style.GridCell{
		Value:        "[" + "NumericalOrder" + "]",
		CellProperty: style.GridCellProperty{},
	}
	paymentStatusCell := style.GridCell{
		Value:        "[" + "PaymentStatus" + "]",
		Format:       "#,0.00",
		CellProperty: style.GridCellProperty{},
	}
	paymentAmountCell := style.GridCell{
		Value:        "[" + "PaymentAmount" + "]",
		CellProperty: style.GridCellProperty{},
	}
	consigneeCell := style.GridCell{
		Value:        "[" + "Consignee" + "]",
		CellProperty: style.GridCellProperty{},
	}
	g.RowCollection = append(g.RowCollection, style.GridRow{
		IsBindingRow: true,
		Height:       30,
		CellCollection: []style.GridCell{
			dataDateCell,
			numericalOrderCell,
			paymentStatusCell,
			paymentAmountCell,
			consigneeCell,
		},
	})
	g.FrozenRows = 2
	g.ColumnWidthCollection = []float64{0.2, 0.15, 0.15, 0.15, 0.15}

	return define, g
}

func GetTestDefine() grid.ReportResult {
	var reportResult grid.ReportResult
	jsonStr := `{
	"isSuccess": true,
	"messageType": "success",
	"message": "",
	"data": {
		"activeSheet": null,
		"sheets": [{
			"name": "Sheet1",
			"rows": [{
				"index": 0,
				"height": 21,
				"cells": [{
					"index": 0,
					"value": "日期",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 1,
					"value": "核算单元",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 2,
					"value": "单据号",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 3,
					"value": "摘要",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 4,
					"value": "增加额",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 5,
					"value": null,
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 6,
					"value": null,
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 7,
					"value": null,
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 8,
					"value": "减少额",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 9,
					"value": null,
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 10,
					"value": null,
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 11,
					"value": "应收账款",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 12,
					"value": null,
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 13,
					"value": null,
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 14,
					"value": "预收账款",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 15,
					"value": "期末金额",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				}]
			},
			{
				"index": 1,
				"height": 38,
				"cells": [{
					"index": 0,
					"value": null,
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 1,
					"value": null,
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 2,
					"value": null,
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 3,
					"value": null,
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 4,
					"value": "销售额",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 5,
					"value": "现场折扣",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 6,
					"value": "月度折扣",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 7,
					"value": "小计",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 8,
					"value": "实收货款",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 9,
					"value": "往来冲抵",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 10,
					"value": "小计",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 11,
					"value": "应收货款",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 12,
					"value": "应收其他款",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 13,
					"value": "小计",
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 14,
					"value": null,
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 15,
					"value": null,
					"textAlign": "center",
					"verticalAlign": "center",
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": true,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				}]
			},
			{
				"index": 2,
				"height": 28,
				"cells": [{
					"index": 0,
					"value": "2017-05-31",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "DataDate",
					"link": null
				},
				{
					"index": 1,
					"value": "",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "TicketedPointName",
					"link": null
				},
				{
					"index": 2,
					"value": "0",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "Number",
					"link": null
				},
				{
					"index": 3,
					"value": "期初结存",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "SettleSummaryName",
					"link": null
				},
				{
					"index": 4,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "SalesAmount",
					"link": null
				},
				{
					"index": 5,
					"value": 0.00000000,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "DiscountAmount",
					"link": null
				},
				{
					"index": 6,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YDZK",
					"link": null
				},
				{
					"index": 7,
					"value": 0.00000000,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 8,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "RealAmount",
					"link": null
				},
				{
					"index": 9,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "WLCD",
					"link": null
				},
				{
					"index": 10,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 11,
					"value": -4580778023.03,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": "#,0.00",
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSHK",
					"link": null
				},
				{
					"index": 12,
					"value": 872577.84,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSQT",
					"link": null
				},
				{
					"index": 13,
					"value": -4579905445.19,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 14,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSZK",
					"link": null
				}]
			},
			{
				"index": 3,
				"height": 28,
				"cells": [{
					"index": 0,
					"value": "2017-06-01",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "DataDate",
					"link": null
				},
				{
					"index": 1,
					"value": null,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "TicketedPointName",
					"link": null
				},
				{
					"index": 2,
					"value": "20170600002",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "Number",
					"link": null
				},
				{
					"index": 3,
					"value": null,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "SettleSummaryName",
					"link": null
				},
				{
					"index": 4,
					"value": 101000.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "SalesAmount",
					"link": null
				},
				{
					"index": 5,
					"value": 0.00000000,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "DiscountAmount",
					"link": null
				},
				{
					"index": 6,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YDZK",
					"link": null
				},
				{
					"index": 7,
					"value": 101000.00000000,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 8,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "RealAmount",
					"link": null
				},
				{
					"index": 9,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "WLCD",
					"link": null
				},
				{
					"index": 10,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 11,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": "#,0.00",
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSHK",
					"link": null
				},
				{
					"index": 12,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSQT",
					"link": null
				},
				{
					"index": 13,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 14,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSZK",
					"link": null
				}]
			},
			{
				"index": 4,
				"height": 28,
				"cells": [{
					"index": 0,
					"value": "2017-06-02",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "DataDate",
					"link": null
				},
				{
					"index": 1,
					"value": null,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "TicketedPointName",
					"link": null
				},
				{
					"index": 2,
					"value": "20170600003",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "Number",
					"link": null
				},
				{
					"index": 3,
					"value": null,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "SettleSummaryName",
					"link": null
				},
				{
					"index": 4,
					"value": 6000.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "SalesAmount",
					"link": null
				},
				{
					"index": 5,
					"value": 0.00000000,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "DiscountAmount",
					"link": null
				},
				{
					"index": 6,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YDZK",
					"link": null
				},
				{
					"index": 7,
					"value": 6000.00000000,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 8,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "RealAmount",
					"link": null
				},
				{
					"index": 9,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "WLCD",
					"link": null
				},
				{
					"index": 10,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 11,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": "#,0.00",
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSHK",
					"link": null
				},
				{
					"index": 12,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSQT",
					"link": null
				},
				{
					"index": 13,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 14,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSZK",
					"link": null
				}]
			},
			{
				"index": 5,
				"height": 28,
				"cells": [{
					"index": 0,
					"value": "2017-06-02",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "DataDate",
					"link": null
				},
				{
					"index": 1,
					"value": null,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "TicketedPointName",
					"link": null
				},
				{
					"index": 2,
					"value": "20170600005",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "Number",
					"link": null
				},
				{
					"index": 3,
					"value": null,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "SettleSummaryName",
					"link": null
				},
				{
					"index": 4,
					"value": 2500.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "SalesAmount",
					"link": null
				},
				{
					"index": 5,
					"value": 0.00000000,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "DiscountAmount",
					"link": null
				},
				{
					"index": 6,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YDZK",
					"link": null
				},
				{
					"index": 7,
					"value": 2500.00000000,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 8,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "RealAmount",
					"link": null
				},
				{
					"index": 9,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "WLCD",
					"link": null
				},
				{
					"index": 10,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 11,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": "#,0.00",
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSHK",
					"link": null
				},
				{
					"index": 12,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSQT",
					"link": null
				},
				{
					"index": 13,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 14,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSZK",
					"link": null
				}]
			},
			{
				"index": 6,
				"height": 28,
				"cells": [{
					"index": 0,
					"value": "2017-06-02",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "DataDate",
					"link": null
				},
				{
					"index": 1,
					"value": null,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "TicketedPointName",
					"link": null
				},
				{
					"index": 2,
					"value": "20170600006",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "Number",
					"link": null
				},
				{
					"index": 3,
					"value": null,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "SettleSummaryName",
					"link": null
				},
				{
					"index": 4,
					"value": 11110.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "SalesAmount",
					"link": null
				},
				{
					"index": 5,
					"value": 0.00000000,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "DiscountAmount",
					"link": null
				},
				{
					"index": 6,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YDZK",
					"link": null
				},
				{
					"index": 7,
					"value": 11110.00000000,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 8,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "RealAmount",
					"link": null
				},
				{
					"index": 9,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "WLCD",
					"link": null
				},
				{
					"index": 10,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 11,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": "#,0.00",
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSHK",
					"link": null
				},
				{
					"index": 12,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSQT",
					"link": null
				},
				{
					"index": 13,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": null,
					"link": null
				},
				{
					"index": 14,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": null,
					"columnName": "YSZK",
					"link": null
				}]
			},
			{
				"index": 7,
				"height": 28,
				"cells": [{
					"index": 0,
					"value": "总计",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": "DataDate",
					"link": null
				},
				{
					"index": 1,
					"value": "",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": "TicketedPointName",
					"link": null
				},
				{
					"index": 2,
					"value": "",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": "Number",
					"link": null
				},
				{
					"index": 3,
					"value": "",
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": "SettleSummaryName",
					"link": null
				},
				{
					"index": 4,
					"value": 120610.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": "SalesAmount",
					"link": null
				},
				{
					"index": 5,
					"value": 0.00000000,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": "DiscountAmount",
					"link": null
				},
				{
					"index": 6,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": "YDZK",
					"link": null
				},
				{
					"index": 7,
					"value": 120610.00000000,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": null,
					"link": null
				},
				{
					"index": 8,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": "RealAmount",
					"link": null
				},
				{
					"index": 9,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": "WLCD",
					"link": null
				},
				{
					"index": 10,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": null,
					"link": null
				},
				{
					"index": 11,
					"value": -4580778023.03,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": "#,0.00",
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": "YSHK",
					"link": null
				},
				{
					"index": 12,
					"value": 872577.84,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": "YSQT",
					"link": null
				},
				{
					"index": 13,
					"value": -4579905445.19,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": null,
					"link": null
				},
				{
					"index": 14,
					"value": 0.00,
					"textAlign": null,
					"verticalAlign": null,
					"wrap": false,
					"italic": false,
					"formula": null,
					"format": null,
					"fontSize": 0,
					"fontFamily": null,
					"enable": false,
					"color": null,
					"borderTop": null,
					"borderRight": null,
					"borderLeft": null,
					"borderBottom": null,
					"bold": false,
					"background": "#FFFFFF",
					"columnName": "YSZK",
					"link": null
				}]
			}],
			"columns": [{
				"index": 0,
				"width": 113.0
			},
			{
				"index": 1,
				"width": 122.0
			},
			{
				"index": 2,
				"width": 127.0
			},
			{
				"index": 3,
				"width": 135.0
			},
			{
				"index": 4,
				"width": 88.0
			},
			{
				"index": 5,
				"width": 81.0
			},
			{
				"index": 6,
				"width": 87.0
			},
			{
				"index": 7,
				"width": 93.0
			},
			{
				"index": 8,
				"width": 86.0
			},
			{
				"index": 9,
				"width": 85.0
			},
			{
				"index": 10,
				"width": 90.0
			},
			{
				"index": 11,
				"width": 86.0
			},
			{
				"index": 12,
				"width": 88.0
			},
			{
				"index": 13,
				"width": 83.0
			},
			{
				"index": 14,
				"width": 88.0
			},
			{
				"index": 15,
				"width": 88.0
			}],
			"selections": "P8:P8",
			"activeCell": "L3:L3",
			"frozenRows": 0,
			"frozenColumns": 0,
			"hyperLinks": null,
			"mergedCells": ["A1:A2",
			"B1:B2",
			"C1:C2",
			"D1:D2",
			"O1:O2",
			"P1:P2",
			"E1:H1",
			"I1:K1",
			"L1:N1"],
			"showGridLines": true
		}],
		"excel": null,
		"pdf": null,
		"propertyList": null,
		"warningInfoList": null,
		"parameterList": null
	}
}`
	if err := json.Unmarshal([]byte(jsonStr), &reportResult); err != nil {
		return grid.ReportResult{
			IsSuccess: false,
			Message:   err.Error(),
		}
	}

	return reportResult
}
